<?php get_header(); ?>
<main class="container"><section class="hero"><h1>Before / After - 5 imagini prelucrate</h1><p>Demonstrație de prelucrare: corecție cromatică, contrast, retuș, efect de tip liquify (warp/perspective) și claritate.</p></section>
<div class="grid edit-grid">
  <article class="card pair"><h3>Imagine 1</h3><div class="cols"><div><p class="meta">Before</p><img class="before" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/tech-desk.svg'); ?>" alt="before 1"></div><div><p class="meta">After (cromatică + contrast)</p><img class="after-1" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/tech-desk.svg'); ?>" alt="after 1"></div></div></article>
  <article class="card pair"><h3>Imagine 2</h3><div class="cols"><div><p class="meta">Before</p><img class="before" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/headphones.svg'); ?>" alt="before 2"></div><div><p class="meta">After (tonuri + retuș)</p><img class="after-2" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/headphones.svg'); ?>" alt="after 2"></div></div></article>
  <article class="card pair"><h3>Imagine 3</h3><div class="cols"><div><p class="meta">Before</p><img class="before" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/smartwatch.svg'); ?>" alt="before 3"></div><div><p class="meta">After (claritate + accent local)</p><img class="after-3" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/smartwatch.svg'); ?>" alt="after 3"></div></div></article>
  <article class="card pair"><h3>Imagine 4</h3><div class="cols"><div><p class="meta">Before</p><img class="before" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/keyboard.svg'); ?>" alt="before 4"></div><div><p class="meta">After (warp/liquify-like)</p><img class="after-4" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/keyboard.svg'); ?>" alt="after 4"></div></div></article>
  <article class="card pair"><h3>Imagine 5</h3><div class="cols"><div><p class="meta">Before</p><img class="before" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/camera.svg'); ?>" alt="before 5"></div><div><p class="meta">After (cromatică + perspectivă)</p><img class="after-5" src="<?php echo esc_url(get_template_directory_uri() . '/assets/images/camera.svg'); ?>" alt="after 5"></div></div></article>
</div>
</main>
<?php get_footer(); ?>
